version: '3'
services:
    client:
        build: ./time-capsule-client
        environment:
            - VUE_APP_API_URI=http://localhost:5000
        ports:
            - '59125:59125'
            - '5000:5000'
            - '8080:80'
    server:
        network_mode: 'service:client'
        build: ./time-capsule-server
        environment:
            - APPID=<APPID>
            - APPKEY=<APPKEY>
    marytts:
        network_mode: 'service:client'
        build: ./marytts-server
